package model

// Stats holds computed cycle-time and velocity metrics.
type Stats struct {
	TotalCompleted               int
	ActiveNow                    int
	AvgCycleTimeMinutes          float64
	FeaturesCompleted            int
	FixesCompleted               int
	CompletedToday               int
	CompletedThisWeek            int
	CostUSDToday                 float64
	CostUSDWeek                  float64
	CostUSDCycle                 float64
	CostUSDTotal                 float64
	CostUSDAvg                   float64
	CostTasks                    int
	BudgetUSDToday               float64
	BudgetUSDWeek                float64
	BudgetUSDCycle               float64
	BudgetUSDTotal               float64
	BudgetUSDAvg                 float64
	BudgetTasks                  int
	BudgetUSDProductToday        float64
	BudgetUSDProductWeek         float64
	BudgetUSDProductCycle        float64
	BudgetUSDInfraToday          float64
	BudgetUSDInfraWeek           float64
	BudgetUSDInfraCycle          float64
	OnDemandUSDToday             float64
	OnDemandUSDWeek              float64
	OnDemandUSDCycle             float64
	BudgetUSDOpen                float64
	CostUSDOpen                  float64
	OnDemandUSDOpen              float64
	BudgetUSDResearchToday       float64
	BudgetUSDResearchWeek        float64
	BudgetUSDResearchCycle       float64
	BudgetUSDResearchOpen        float64
	CostUSDResearchToday         float64
	CostUSDResearchWeek          float64
	CostUSDResearchCycle         float64
	CostUSDResearchOpen          float64
	ResearchCompleted            int
	ResearchCompletedToday       int
	ResearchCompletedWeek        int
	BillingCycleStart            string
	PlanPriceUSD                 *float64
	CursorModelsPctToday         float64
	OtherModelsPctToday          float64
	CursorModelsPctCycle         float64
	OtherModelsPctCycle          float64
	CursorModelsPctOpen          float64
	OtherModelsPctOpen           float64
	CursorModelsPctProductCycle  float64
	OtherModelsPctProductCycle   float64
	CursorModelsPctInfraCycle    float64
	OtherModelsPctInfraCycle     float64
	CursorModelsPctResearchToday float64
	OtherModelsPctResearchToday  float64
	CursorModelsPctResearchCycle float64
	OtherModelsPctResearchCycle  float64
	CursorModelsPctResearchOpen  float64
	OtherModelsPctResearchOpen   float64
	Hours                        []HourSpend
	Days                         []HourSpend
}
